# Generated by Django 5.1 on 2024-08-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, height_field=40, null=True, upload_to='', width_field=40),
        ),
    ]
